### PR TITLE
Move tray app to .NET 4.7.2

### LINKED ISSUE #125: [Issue]: Warning for Windows Server 2019 users
### Please describe your bug

When updating from old versions (Mine was 10.8.13) to version 10.9.2, Jellyfin 10.9.2 requires .net version 4.8.1 which is not supported on Windows Server 2019.

.net 4.8.1 only supports Windows Server 2022, see:
https://learn.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

### Reproduction Steps

I uninstalled 10.9.2 and installed 10.8.13 again, copied the programdata and programfiles folders (My Jellyfin Backup folders) back, now it works again.

Best way (for me) is to make a new Win 2022 Server (Virtual Machine) with Jellyfin 10.9.2 and then migrate existing settings or create users and settings again..etc on the new server, when done port forward to the new server.

### Jellyfin Version

10.8.13

### if other:

_No response_

### Environment

```markdown
- OS:Windows Server 2019
- Virtualization:Hyper-V
- .Net version Required: 4.8.1 for Jellyfin Win Server 10.9.2
```

### Jellyfin logs

```shell
No log needed.
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by anthonylavado**
This adds x64 Server 2019 support, for those who had issues.

We'll revisit a hybrid approach when we start building installer and tray for ARM.

Fixes #125 #119

### CODE REVIEW

**Review by crobibero — COMMENTED** [review]
Does CI/nsis need to be updated for the subpath support?

**Comment by nielsvanvelzen** [comment]
Doesn't the tray app try to find `jellyfin.exe` it its own directory (CWD)? That would obviously fail after this PR.

**Comment by anthonylavado** [comment]
> Does CI/nsis need to be updated for the subpath support?

NSIS does have paths for the tray app to make shortcuts, those are updated for the sub folder in here.

The CI has the same subfolder specified for the output which should mean it's okay.

**Comment by anthonylavado** [comment]
> Doesn't the tray app try to find `jellyfin.exe` it its own directory (CWD)? That would obviously fail after this PR.

Good catch, I'll update that.

**Comment by anthonylavado** [comment]
@nielsvanvelzen Looks like we already covered that case a long time ago:
https://github.com/jellyfin/jellyfin-server-windows/master/Jellyfin.Windows.Tray/TrayApplicationContext.cs#L159

IIRC the tray app used to be in its own folder, a long time ago 🙂

**Comment by anthonylavado** [comment]
I just realized that `windows-latest` has a 4.7.2 targeting pack, but doesn't list it in .NET Core Tools (see [here](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#net-core-tools)). Should I kick this back to 2019?

**Review by crobibero — APPROVED** [review]

**Pull request merged**
